SELECT I.ID, N.FISH_NAME, I.LENGTH
FROM FISH_INFO I
JOIN FISH_NAME_INFO N
ON N.FISH_TYPE = I.FISH_TYPE
WHERE (I.LENGTH,I.FISH_TYPE) IN (
    SELECT MAX(LENGTH),FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)