name: Auto Blog Post (BaekjoonHub)

on:
  push:
    branches:
      - main
    paths:
      - "백준/**"
      - "프로그래머스/**"

jobs:
  auto-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2   # 이전 커밋과 diff 비교용

      - name: Detect newly added problem directories
        run: |
          echo "🔍 변경된 파일 탐색 중..."

          git config --global core.quotepath false

          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.sha }}"

          echo "🔁 Diff range: $BEFORE → $AFTER"

          git diff --name-only --diff-filter=A "$BEFORE" "$AFTER" \
          | grep 'README.md$' \
          | while read -r file; do
              dirname "$file"
            done \
          | sort -u > problem_dirs.txt

          echo "📁 새로 추가된 문제 폴더:"
          cat problem_dirs.txt || true



      - name: Auto post new problems
        env:
          BLOG_API_URL: ${{ secrets.BLOG_API_URL }}
          BLOG_API_KEY: ${{ secrets.BLOG_API_KEY }}
          BLOG_PROXY: ${{ secrets.BLOG_PROXY}}
        run: |
          if [ ! -s problem_dirs.txt ]; then
            echo "📭 새로 추가된 문제가 없습니다. 종료합니다."
            exit 0
          fi

          while read PROBLEM_PATH; do
            echo "🚀 자동 포스팅 시작: $PROBLEM_PATH"
            PROBLEM_PATH="$PROBLEM_PATH" python .github/scripts/post_single_problem.py

            echo "⏱ 5초 대기..."
            sleep 5
          done < problem_dirs.txt


